"""add calendar_type to calendars table

Revision ID: 2db828c08be9
Revises: fddac6ca9795
Create Date: 2025-06-30 21:58:48.630456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db828c08be9'
down_revision: Union[str, Sequence[str], None] = 'fddac6ca9795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendars', sa.Column('calendar_type', sa.Enum('PERSONAL', 'GENERAL', name='calendartype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendars', 'calendar_type')
    # ### end Alembic commands ###
