"""Add foreign key indexes and composite indexes for performance optimization

Revision ID: 8763bf7f0ac6
Revises: df619e1f0c40
Create Date: 2025-07-01 21:16:50.349851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8763bf7f0ac6'
down_revision: Union[str, Sequence[str], None] = 'df619e1f0c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_calendars_owner_id'), 'calendars', ['owner_id'], unique=False)
    op.create_index('idx_event_calendar_time', 'events', ['calendar_id', 'start_time'], unique=False)
    op.create_index('idx_event_creator', 'events', ['creator_id'], unique=False)
    op.create_index('idx_event_start_time', 'events', ['start_time'], unique=False)
    op.create_index(op.f('ix_events_calendar_id'), 'events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_events_creator_id'), 'events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_list_items_creator_id'), 'list_items', ['creator_id'], unique=False)
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_lists_calendar_id'), 'lists', ['calendar_id'], unique=False)
    op.create_index('idx_vote_list_item', 'votes', ['list_item_id'], unique=False)
    op.create_index('idx_vote_user', 'votes', ['user_id'], unique=False)
    op.create_index('idx_vote_user_item_unique', 'votes', ['user_id', 'list_item_id'], unique=True)
    op.create_index(op.f('ix_votes_list_item_id'), 'votes', ['list_item_id'], unique=False)
    op.create_index(op.f('ix_votes_user_id'), 'votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_user_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_list_item_id'), table_name='votes')
    op.drop_index('idx_vote_user_item_unique', table_name='votes')
    op.drop_index('idx_vote_user', table_name='votes')
    op.drop_index('idx_vote_list_item', table_name='votes')
    op.drop_index(op.f('ix_lists_calendar_id'), table_name='lists')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_creator_id'), table_name='list_items')
    op.drop_index(op.f('ix_events_creator_id'), table_name='events')
    op.drop_index(op.f('ix_events_calendar_id'), table_name='events')
    op.drop_index('idx_event_start_time', table_name='events')
    op.drop_index('idx_event_creator', table_name='events')
    op.drop_index('idx_event_calendar_time', table_name='events')
    op.drop_index(op.f('ix_calendars_owner_id'), table_name='calendars')
    # ### end Alembic commands ###
